// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/footer/AppFooter.vue')['default']
    AppInput: typeof import('./components/common/AppInput.vue')['default']
    AppTextarea: typeof import('./components/common/AppTextarea.vue')['default']
    Contact: typeof import('./components/contact/Contact.vue')['default']
    FullScreenLoader: typeof import('./components/misc/FullScreenLoader.vue')['default']
    Hero: typeof import('./components/hero/Hero.vue')['default']
    HeroIntro: typeof import('./components/hero/HeroIntro.vue')['default']
    Navbar: typeof import('./components/navigation/Navbar.vue')['default']
    Projects: typeof import('./components/projects/Projects.vue')['default']
    README: typeof import('./components/README.md')['default']
    SectionBlock: typeof import('./components/common/SectionBlock.vue')['default']
    SectionHeader: typeof import('./components/common/SectionHeader.vue')['default']
    Services: typeof import('./components/services/Services.vue')['default']
  }
}

export { }
