// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/footer/AppFooter.vue')['default']
    AppInput: typeof import('./components/common/AppInput.vue')['default']
    AppTextarea: typeof import('./components/common/AppTextarea.vue')['default']
    Brain: typeof import('./components/icons/Brain.vue')['default']
    Chevron: typeof import('./components/icons/Chevron.vue')['default']
    CloseButton: typeof import('./components/common/CloseButton.vue')['default']
    Contact: typeof import('./components/portfolio/contact/Contact.vue')['default']
    Design: typeof import('./components/icons/Design.vue')['default']
    FullScreenLoader: typeof import('./components/misc/FullScreenLoader.vue')['default']
    Globe: typeof import('./components/icons/Globe.vue')['default']
    Hamburger: typeof import('./components/navigation/mobile-menu/Hamburger.vue')['default']
    Hero: typeof import('./components/portfolio/hero/Hero.vue')['default']
    HeroIntro: typeof import('./components/portfolio/hero/HeroIntro.vue')['default']
    Learn: typeof import('./components/icons/Learn.vue')['default']
    MobileMenu: typeof import('./components/navigation/mobile-menu/MobileMenu.vue')['default']
    Navbar: typeof import('./components/navigation/Navbar.vue')['default']
    Projects: typeof import('./components/portfolio/projects/Projects.vue')['default']
    ProjectSwiper: typeof import('./components/portfolio/projects/ProjectSwiper.vue')['default']
    ProjectSwitch: typeof import('./components/portfolio/projects/ProjectSwitch.vue')['default']
    ProjectTop: typeof import('./components/portfolio/projects/ProjectTop.vue')['default']
    README: typeof import('./components/README.md')['default']
    SectionBlock: typeof import('./components/common/SectionBlock.vue')['default']
    SectionHeader: typeof import('./components/common/SectionHeader.vue')['default']
    Services: typeof import('./components/portfolio/services/Services.vue')['default']
    SlideChanger: typeof import('./components/misc/SlideChanger.vue')['default']
    SliderArrow: typeof import('./components/icons/SliderArrow.vue')['default']
    Testimonials: typeof import('./components/portfolio/testimonials/Testimonials.vue')['default']
  }
}

export { }
